language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - cp README.md README.rst

install:
  - pip install -e .

script: python -c "import nanolyse"

notifications:
  email: false
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/4b1c45cea6826ce475c2
